import AppKit
import Defaults
import Foundation

/// Built-in pasteboard type rules shared by the fast main-actor gate, the
/// authoritative ingest filter, and its tests.
enum IngestFilterRules {
  static let supportedTypes: Set<String> = [
    NSPasteboard.PasteboardType.fileURL.rawValue,
    NSPasteboard.PasteboardType.heic.rawValue,
    NSPasteboard.PasteboardType.html.rawValue,
    NSPasteboard.PasteboardType.jpeg.rawValue,
    NSPasteboard.PasteboardType.png.rawValue,
    NSPasteboard.PasteboardType.rtf.rawValue,
    NSPasteboard.PasteboardType.string.rawValue,
    NSPasteboard.PasteboardType.tiff.rawValue
  ]

  static let builtInIgnoredTypes: Set<String> = [
    NSPasteboard.PasteboardType.autoGenerated.rawValue,
    NSPasteboard.PasteboardType.concealed.rawValue,
    NSPasteboard.PasteboardType.transient.rawValue
  ]
}

/// Injectable, value-type snapshot of the configuration the ingest filter needs.
///
/// `IngestConfig` captures the live `Defaults` values and shared
/// `IngestFilterRules` as plain values so `filterContents` has no global reads.
/// The ingest actor builds the snapshot on the main actor before filtering.
struct IngestConfig: Sendable, Equatable {
  /// Raw values of `IngestFilterRules.supportedTypes`.
  var supportedTypes: Set<String>

  /// RawValues of `Defaults[.enabledPasteboardTypes]`. Used both to drop disabled
  /// types and as the "is anything we care about enabled" gate.
  var enabledTypes: Set<String>

  /// `IngestFilterRules.builtInIgnoredTypes` union
  /// `Defaults[.ignoredPasteboardTypes]`.
  var ignoredTypes: Set<String>

  /// Mirrors `HistoryItemContent.maxValueSize`. A content whose `value.count`
  /// exceeds this is dropped.
  var maxValueSize: Int

  /// RTF/HTML parsing limit. The production config uses `512 * 1024`; larger
  /// payloads count as "rich text present" without parsing.
  var richTextParsingLimit: Int

  /// Maximum string byte count scanned against ignore regexes. The production
  /// config uses `2_000`; larger strings are not regex-tested.
  var regularExpressionInputLimit: Int

  /// `Defaults[.ignoreRegexp]`. Each safe pattern is matched against the `.string`
  /// content; a match discards the whole batch.
  var ignoreRegexp: [String]

  /// `Defaults[.ignoredApps]`. App bundle ids to ignore or (when
  /// `ignoreAllAppsExceptListed` is true) to allow.
  var ignoredApps: [String]

  /// `Defaults[.ignoreAllAppsExceptListed]`. When true, the semantics of
  /// `ignoredApps` flip from a block list to an allow list.
  var ignoreAllAppsExceptListed: Bool

  /// `HistoryItem.titlePreviewLimit`. The empty-string rule only fires when the
  /// `.string` payload is at most this large.
  var titlePreviewLimit: Int
}

/// Per-copy settings captured while `Clipboard` is already on the main actor.
///
/// The background ingestor consumes this immutable value without reading UI
/// globals or hopping to `MainActor` merely to obtain configuration.
struct IngestPolicy: Sendable, Equatable {
  let filter: IngestConfig
  let historyLimit: Int
  let showSpecialSymbols: Bool

  /// Captures the live defaults that affect one ingest.
  @MainActor
  static func liveSnapshot() -> IngestPolicy {
    let enabledTypes = Set(Defaults[.enabledPasteboardTypes].map(\.rawValue))
    let ignoredTypes = IngestFilterRules.builtInIgnoredTypes
      .union(Defaults[.ignoredPasteboardTypes])

    return IngestPolicy(
      filter: IngestConfig(
        supportedTypes: IngestFilterRules.supportedTypes,
        enabledTypes: enabledTypes,
        ignoredTypes: ignoredTypes,
        maxValueSize: HistoryItemContent.maxValueSize,
        richTextParsingLimit: 512 * 1_024,
        regularExpressionInputLimit: 2_000,
        ignoreRegexp: Defaults[.ignoreRegexp],
        ignoredApps: Defaults[.ignoredApps],
        ignoreAllAppsExceptListed: Defaults[.ignoreAllAppsExceptListed],
        titlePreviewLimit: HistoryItem.titlePreviewLimit
      ),
      historyLimit: max(1, Defaults[.size]),
      showSpecialSymbols: Defaults[.showSpecialSymbols]
    )
  }

  /// Deterministic baseline for synthetic requests that never enter the
  /// production background ingestor (DTO/index/adapter tests).
  static let standard = IngestPolicy(
    filter: IngestConfig(
      supportedTypes: IngestFilterRules.supportedTypes,
      enabledTypes: IngestFilterRules.supportedTypes,
      ignoredTypes: IngestFilterRules.builtInIgnoredTypes,
      maxValueSize: ClipboardContentSizeLimit.defaultMegabytes
        * ClipboardContentSizeLimit.bytesPerMegabyte,
      richTextParsingLimit: 512 * 1_024,
      regularExpressionInputLimit: 2_000,
      ignoreRegexp: [],
      ignoredApps: [],
      ignoreAllAppsExceptListed: false,
      titlePreviewLimit: HistoryItem.titlePreviewLimit
    ),
    historyLimit: 200,
    showSpecialSymbols: true
  )
}

/// AppKit-affine rich-text operations required for a given content batch.
///
/// Planning is pure and conservative: a bit is set only when the matching
/// `NSAttributedString` parser can actually be reached. Oversized rich text is
/// handled without parsing and therefore does not request main-actor work.
struct IngestMainActorPlan: OptionSet, Sendable {
  let rawValue: UInt8

  static let richTextPresence = IngestMainActorPlan(rawValue: 1 << 0)
  static let textProjection = IngestMainActorPlan(rawValue: 1 << 1)

  init(rawValue: UInt8) {
    self.rawValue = rawValue
  }

  init(contents: [ContentDTO], config: IngestConfig) {
    var plan: IngestMainActorPlan = []
    if Self.needsRichTextPresenceParsing(contents, config: config) {
      plan.insert(.richTextPresence)
    }
    if Self.needsRichTextProjection(contents, config: config) {
      plan.insert(.textProjection)
    }
    self = plan
  }

  private static func needsRichTextPresenceParsing(
    _ contents: [ContentDTO],
    config: IngestConfig
  ) -> Bool {
    guard let stringData = firstData(for: .string, in: contents),
          stringData.count <= config.titlePreviewLimit,
          stringData.stringPrefix(maxBytes: config.titlePreviewLimit)?
          .trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == true else {
      return false
    }

    if let rtf = firstData(for: .rtf, in: contents) {
      return rtf.count <= config.richTextParsingLimit
    }
    if let html = firstData(for: .html, in: contents) {
      return html.count <= config.richTextParsingLimit
    }
    return false
  }

  private static func needsRichTextProjection(
    _ contents: [ContentDTO],
    config: IngestConfig
  ) -> Bool {
    guard hasSmallRichText(in: contents, limit: config.richTextParsingLimit) else {
      return false
    }
    guard !hasUsableFileURL(in: contents) else { return false }
    guard let stringData = firstData(for: .string, in: contents) else { return true }

    let titleUsesPlainText = stringData
      .stringPrefix(maxBytes: config.titlePreviewLimit)?.isEmpty == false
    let bodyUsesPlainText = String(data: stringData, encoding: .utf8)?.isEmpty == false
    return !titleUsesPlainText || !bodyUsesPlainText
  }

  private static func hasSmallRichText(in contents: [ContentDTO], limit: Int) -> Bool {
    [.rtf, .html].contains { type in
      guard let data = firstData(for: type, in: contents) else { return false }
      return data.count <= limit
    }
  }

  private static func hasUsableFileURL(in contents: [ContentDTO]) -> Bool {
    let universalClipboard = firstData(for: .universalClipboard, in: contents) != nil
    let concreteTypes: [NSPasteboard.PasteboardType] = [
      .html, .tiff, .png, .jpeg, .rtf, .string, .heic
    ]
    if universalClipboard && concreteTypes.contains(where: {
      firstData(for: $0, in: contents) != nil
    }) {
      return false
    }

    return contents.contains { content in
      content.type == NSPasteboard.PasteboardType.fileURL.rawValue
        && content.value.flatMap {
          URL(dataRepresentation: $0, relativeTo: nil, isAbsolute: true)
        } != nil
    }
  }

  private static func firstData(
    for type: NSPasteboard.PasteboardType,
    in contents: [ContentDTO]
  ) -> Data? {
    contents.first { $0.type == type.rawValue && $0.value != nil }?.value
  }
}

/// Applies the `Clipboard` filtering/ignore rules to an
/// already-materialized, flat `[ContentDTO]`.
///
/// `Clipboard.ingestRequestFromPasteboard()` merges every pasteboard item's
/// contents into a flat request. This function applies the authoritative rules
/// once to that whole batch before persistence.
///
/// Rules are applied in this order:
///
/// 1. **Application ignore** — if `application` matches the configured app list
///    (allow- or block-list depending on `ignoreAllAppsExceptListed`), returns
///    `[]`. A nil `application` is never ignored.
///
/// 2. **Global type gate** — computed over the union of all `ContentDTO.type`
///    values. Returns `[]` if that set is disjoint from `enabledTypes`
///    (nothing we care about) OR not disjoint from `ignoredTypes` (a
///    transient/concealed/auto-generated/custom-ignored marker).
///
/// 3. **Empty-string rule** — if a `.string` content is present and trims to
///    whitespace (within `titlePreviewLimit`) and there is no non-empty RTF/HTML
///    representation, returns `[]`.
///
/// 4. **Regex ignore** — if the `.string` content (when within
///    `regularExpressionInputLimit`) matches any safe `ignoreRegexp` entry,
///    returns `[]`. Unsafe patterns (`Search.isLikelyUnsafeRegularExpression`)
///    are skipped.
///
/// 5. **Type filtering** — drops types not in `supportedTypes ∩ enabledTypes`
///    (disabled types), drops `dyn.`-prefixed and
///    `com.microsoft.ole.source.`-prefixed types, and applies the Microsoft Word
///    bookmark subtraction: when both `com.microsoft.Link-Source` and
///    `com.microsoft.ObjectLink` are present, those two types plus
///    `com.adobe.pdf` are removed.
///
/// 6. **Size cap** — any remaining content whose `value?.count` exceeds
///    `maxValueSize` is dropped.
///
/// This convenience overload performs AppKit rich-text detection on the main
/// actor, then delegates all rules to the pure overload accepting an explicit
/// `richTextPresent` value. The pure empty-string predicate is also exposed as
/// `isEffectivelyEmpty(_:richTextPresent:titlePreviewLimit:)` so the decision can
/// be unit-tested without `NSAttributedString`.
///
/// - Parameters:
///   - raw: The flat, already-merged contents to filter. Order is preserved for
///     surviving contents.
///   - application: Source app bundle id of the copy, or nil if unknown.
///   - config: The configuration snapshot.
/// - Returns: The surviving contents in their original order, or `[]` if any
///   gate rules out the whole batch.
@MainActor
func filterContents(
  _ raw: [ContentDTO],
  application: String?,
  config: IngestConfig
) -> [ContentDTO] {
  filterContents(
    raw,
    application: application,
    config: config,
    richTextPresent: parseRichTextPresence(in: raw, config: config)
  )
}

/// Applies ingest rules using a caller-supplied rich-text presence decision.
/// This overload is pure and is the background actor's ordinary path.
func filterContents(
  _ raw: [ContentDTO],
  application: String?,
  config: IngestConfig,
  richTextPresent: Bool
) -> [ContentDTO] {
  if shouldIgnoreApplication(application, config: config) {
    return []
  }

  let typeSet = Set(raw.map(\.type))
  if shouldIgnoreTypes(typeSet, config: config) {
    return []
  }

  // Empty-string rule: only meaningful when a `.string` content is present.
  // `isEffectivelyEmpty` re-checks that presence internally, so no separate
  // guard is needed here.
  let stringContent = raw.first { $0.type == NSPasteboard.PasteboardType.string.rawValue }
  if isEffectivelyEmpty(
    raw,
    richTextPresent: richTextPresent,
    titlePreviewLimit: config.titlePreviewLimit
  ) {
    return []
  }

  if let stringContent, shouldIgnoreByRegexp(stringContent, config: config) {
    return []
  }

  return raw.filter { content in
    filteredTypeSet(typeSet, config: config).contains(content.type)
      && (content.value?.count ?? 0) <= config.maxValueSize
  }
}

/// Pure predicate for the empty-string rule.
///
/// Returns true only when:
/// - a `.string`-typed content is present,
/// - its payload is at most `titlePreviewLimit` bytes,
/// - that payload trims to an empty string (whitespace/newlines only),
/// - and no rich-text representation is present (`richTextPresent == false`).
///
/// Factored out so the decision can be unit-tested without `NSAttributedString`.
func isEffectivelyEmpty(
  _ contents: [ContentDTO],
  richTextPresent: Bool,
  titlePreviewLimit: Int
) -> Bool {
  guard !richTextPresent else { return false }
  guard let stringContent = contents.first(where: {
    $0.type == NSPasteboard.PasteboardType.string.rawValue
  }) else {
    return false
  }

  guard let data = stringContent.value, data.count <= titlePreviewLimit else {
    return false
  }

  return data.stringPrefix(maxBytes: titlePreviewLimit)?
    .trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == true
}

// MARK: - Rule helpers

/// Returns whether the source app is ignored. A nil bundle id is never ignored.
private func shouldIgnoreApplication(_ application: String?, config: IngestConfig) -> Bool {
  guard let application else { return false }
  if config.ignoreAllAppsExceptListed {
    return !config.ignoredApps.contains(application)
  }
  return config.ignoredApps.contains(application)
}

/// Returns whether the whole batch should be ignored by type: true when the type
/// set is disjoint from enabled types OR not disjoint from ignored types.
private func shouldIgnoreTypes(_ types: Set<String>, config: IngestConfig) -> Bool {
  types.isDisjoint(with: config.enabledTypes) ||
    !types.isDisjoint(with: config.ignoredTypes)
}

/// Returns whether a non-empty RTF or HTML rich-text representation is present.
///
/// Returns true when an RTF or HTML content exists and either exceeds
/// `richTextParsingLimit` (the early-return-true path for oversized payloads) or
/// parses to a non-empty attributed string.
@MainActor
func parseRichTextPresence(in contents: [ContentDTO], config: IngestConfig) -> Bool {
  let rtf = contents.first { $0.type == NSPasteboard.PasteboardType.rtf.rawValue }?.value
  if let rtf {
    guard rtf.count <= config.richTextParsingLimit else { return true }
    if let attributed = NSAttributedString(rtf: rtf, documentAttributes: nil) {
      return !attributed.string.isEmpty
    }
  }

  let html = contents.first { $0.type == NSPasteboard.PasteboardType.html.rawValue }?.value
  if let html {
    guard html.count <= config.richTextParsingLimit else { return true }
    if let attributed = NSAttributedString(html: html, documentAttributes: nil) {
      return !attributed.string.isEmpty
    }
  }

  return false
}

/// Detects the only rich-text presence case that needs no parser: an RTF/HTML
/// payload above the parsing limit is considered present by policy.
func oversizedRichTextPresent(in contents: [ContentDTO], config: IngestConfig) -> Bool {
  contents.contains { content in
    let richTypes = [
      NSPasteboard.PasteboardType.rtf.rawValue,
      NSPasteboard.PasteboardType.html.rawValue
    ]
    return richTypes.contains(content.type)
      && (content.value?.count ?? 0) > config.richTextParsingLimit
  }
}

/// Returns whether the string content should be discarded by an `ignoreRegexp` pattern.
///
/// True when the string content (within `regularExpressionInputLimit`) matches
/// any safe `ignoreRegexp` pattern. Unsafe patterns are skipped; uncompilable
/// patterns are skipped. Regexes are recompiled on each call — correct, if slower
/// than `Clipboard`'s cached map.
private func shouldIgnoreByRegexp(_ stringContent: ContentDTO, config: IngestConfig) -> Bool {
  guard let data = stringContent.value,
        data.count <= config.regularExpressionInputLimit,
        let string = data.stringPrefix(maxBytes: config.regularExpressionInputLimit) else {
    return false
  }

  let range = NSRange(string.startIndex..., in: string)
  for pattern in config.ignoreRegexp {
    guard !Search.isLikelyUnsafeRegularExpression(pattern) else { continue }
    guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
    if regex.numberOfMatches(in: string, range: range) > 0 {
      return true
    }
  }
  return false
}

/// Computes the surviving type set after applying the disabled-type, prefix, and
/// Microsoft Word bookmark rules.
///
/// Only DISABLED types are removed (`disabledTypes = supportedTypes −
/// enabledTypes`): a type is dropped iff it is supported but not enabled. Types
/// that are not in `supportedTypes` at all (custom / app-specific UTIs) are KEPT,
/// so Maccy captures them for round-trip fidelity. Then it drops the `dyn.` and
/// `com.microsoft.ole.source.` prefixes and applies the Microsoft Word bookmark
/// subtraction.
private func filteredTypeSet(_ types: Set<String>, config: IngestConfig) -> Set<String> {
  let dynamicTypePrefix = "dyn."
  let microsoftSourcePrefix = "com.microsoft.ole.source."
  let microsoftLinkSource = "com.microsoft.Link-Source"
  let microsoftObjectLink = "com.microsoft.ObjectLink"
  let pdf = "com.adobe.pdf"

  let disabled = config.supportedTypes.subtracting(config.enabledTypes)
  var result = types
    .subtracting(disabled)
    .filter { !$0.hasPrefix(dynamicTypePrefix) }
    .filter { !$0.hasPrefix(microsoftSourcePrefix) }

  if result.isSuperset(of: [microsoftLinkSource, microsoftObjectLink]) {
    result.subtract([microsoftLinkSource, microsoftObjectLink, pdf])
  }

  return result
}
